evolvedbinary/prosemirror-lwdita

- src/commands.ts
Deleting empty elements while inserting other elements right after them
> Inserting nested elements

- package.json
> Fix workspace name

- .circleci/config.yml
- README.md
- package.json
Update Node version to v20.10.0 and also update the readme and `package.json` engines section.
> Update Node version

- prosemirror-jdita-demo/package.json
- yarn.lock
Removes duplicate `prosemirror-state` entries from `yarn.lock` file.
**NOTE** I just used Yarn to completely re-generate the `yarn.lock` file.
Closes https://github.com/evolvedbinary/prosemirror-jdita/issues/240
> Fix the build 

- .gitignore
- prosemirror-jdita-demo/index.html
- prosemirror-jdita-demo/package.json
- prosemirror-jdita-demo/style/style.scss
- yarn.lock
Updates us to the latest version of parcel.
> Update from Parcel v1 to Parcel v2

- .circleci/config.yml
- package.json
- prosemirror-jdita-demo/cypress.config.ts
- prosemirror-jdita-demo/cypress/e2e/download.cy.ts
- prosemirror-jdita-demo/cypress/fixtures/example.json
- prosemirror-jdita-demo/cypress/support/commands.ts
- prosemirror-jdita-demo/cypress/support/e2e.ts
- prosemirror-jdita-demo/cypress/tsconfig.json
- prosemirror-jdita-demo/package.json
- prosemirror-jdita-demo/src/doc.ts
- prosemirror-jdita/package.json
- yarn.lock
This PR is for adding cypress test for the download.
> Add e2e test to the code

- prosemirror-lwdita-demo/package.json
- prosemirror-lwdita-demo/src/doc.ts
- prosemirror-lwdita/package.json
- prosemirror-lwdita/src/document.ts
- prosemirror-lwdita/src/schema.ts
- prosemirror-lwdita/src/tests/schema.spec.ts
- prosemirror-lwdita/src/tests/test-utils.ts
- prosemirror-lwdita/src/tests/topic.spec.ts
- yarn.lock
Use the new packages `lwdita-ast` and `lwdita-xdita`  and update the imports with any necessary code changes.
> Replace jdita package with lwdita packages

- .yarnrc.yml
- package.json
- plugin-release.js
- prosemirror-lwdita-demo/package.json
- prosemirror-lwdita/package.json
Same simple release plugin that we added to https://github.com/evolvedbinary/lwdita
> Simple release plugin for Yarn

- packages/prosemirror-lwdita-demo/cypress/e2e/download.cy.ts
- packages/prosemirror-lwdita-demo/example-xdita/petal-introduction.xml
- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
- packages/prosemirror-lwdita-demo/src/doc.ts
- packages/prosemirror-lwdita-demo/style/style.scss
Updated default example XML file with Petal content and the default in the example doc.ts file
> Hotfixes for the demo.

- packages/prosemirror-lwdita-demo/cypress/e2e/download.cy.ts
- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
- packages/prosemirror-lwdita/src/document.ts
Prevent the generation process from adding the parent attribute in `xdita`
> Remove parent attribute from xdita

- packages/prosemirror-lwdita-demo/index.html
- packages/prosemirror-lwdita-demo/style/style.scss
Add the logo and improve the header
> Add the EB Logo to the Demo

- packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
This PR adds Petal into the automated commit created by the backend.
it should look like this: https://github.com/evolvedbinary/prosemirror-lwdita/commit/c11d803179d0871af2471d9851dd96bded53d062
* checkout the branch `octokit/create-pr`
* install any new dependencies by running `yarn install`
* add environment variables to your code ( DM me to get them).
* start the server using `yarn start:backend`
* copy the token you got before from the auth process, or generate a new one by making a request to `https://github.com/login/oauth/authorize?client_id=` add the client id.
* make a `POST` request to 'http://localhost:3000/api/github/integration`  as example bellow or follow the docs in the README.
```sh
curl --location 'localhost:3000/api/github/integration' \
--header 'Content-Type: …
```
> Add GitHub Petal App as committer

- .circleci/config.yml
- package.json
- packages/prosemirror-lwdita-backend/.mocharc.json
- packages/prosemirror-lwdita-backend/package.json
- packages/prosemirror-lwdita-backend/src/api/controller/github.controller.ts
- packages/prosemirror-lwdita-backend/src/api/routes/github.router.ts
- packages/prosemirror-lwdita-backend/src/tests/github.controller.spec.ts
- packages/prosemirror-lwdita-backend/src/tests/githubRouter.spec.ts
- packages/prosemirror-lwdita-backend/src/tests/test.spec.ts
- yarn.lock
This PR adds tests for the GitHub router and the GitHub controller.
* checkout the branch
* install new dependencies `yarn instal`
* run the tests `yarn run test:backend`
* check the backend test on CI
> Unit tests for the backend API

- packages/prosemirror-lwdita-demo/cypress/e2e/pr-dialog.cy.ts
- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
- packages/prosemirror-lwdita-demo/style/style.scss
- packages/prosemirror-lwdita/src/commands.ts
This PR adds a user dialog for submitting the changes for the GitHub integration:
```
rm -rf node_modules/
yarn install
yarn clean && yarn build & yarn start:demo
```
1. Insert a URL with valid parameters, i.e. `http://localhost:1234/?ghrepo=ghrepo1&source=source1&referer=repo1`
2. Click on button "Publish file..."
3. Insert a title and and optionally a description into the form.
4. Click submit
5. Check the console for the correct form data.
```
yarn test:demo
```
> Create a user dialog for PR metadata

- package.json
Added missing task for prosemirror-lwdita-backend package to the `yarn clean` script.
> Add "remove dist folder" task (`yarn clean`) to prosemirro-lwdita-backend script

- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
- packages/prosemirror-lwdita-demo/src/example.ts
- packages/prosemirror-lwdita/src/commands.ts
- packages/prosemirror-lwdita/src/github-integration/github.plugin.ts
- packages/prosemirror-lwdita/tests/github.plugin.spec.ts
Creates a PR from the user contribution and submit as a PR.
* Checkout the branch
* Install dependencies `yarn install`
* Enable `cors` on the backend (This is just for testing)
* Start the backend `yarn run start:backend`
* Start the demo `yarn run start:demo`
* make a request to `http://localhost:1234/?ghrepo=evolvedbinary/prosemirror-lwdita&source=packages/prosemirror-lwdita-demo/example-xdita/02-short-file.xml&referer=htwsrhtshrts`
* Edit the file
* Click on publish button
* Fill out the from
* Click Submit
* Check the console for the PR url
* Check your PRs on GitHub.
> Submit PR from user contribution

- packages/prosemirror-lwdita-demo/cypress/e2e/download.cy.ts
- packages/prosemirror-lwdita-demo/cypress/e2e/image.cy.ts
- packages/prosemirror-lwdita-demo/cypress/e2e/newline.cy.ts
- packages/prosemirror-lwdita-demo/index.html
- packages/prosemirror-lwdita-demo/src/doc.ts
- packages/prosemirror-lwdita-demo/src/example.ts
- packages/prosemirror-lwdita-demo/style/fonts/petal.svg
- packages/prosemirror-lwdita-demo/style/icons.css
- packages/prosemirror-lwdita-demo/style/style.scss
- packages/prosemirror-lwdita/index.js
- packages/prosemirror-lwdita/scripts/fix.js
- plugin-release.js
This PR adds missing licence headers to source code files.
> Add missing licence headers

- packages/prosemirror-lwdita-backend/README.md
- packages/prosemirror-lwdita-demo/README.md
Adds instructions on how to deploy to [petal](https://petal.evolvedbinary.com/), and also adds the instruction on how to deploy the backend API.
> How to deploy on production

- packages/prosemirror-lwdita-demo/.parcelrc
- packages/prosemirror-lwdita-demo/README.md
- packages/prosemirror-lwdita-demo/package.json
- packages/prosemirror-lwdita-demo/src/example.ts
- packages/prosemirror-lwdita/src/github-integration/request.ts
- yarn.lock
The CI is failing for this reason:
```
src/commands.ts:26:30 - error TS7016: Could not find a declaration file for module '@evolvedbinary/prosemirror-lwdita-localization'. '/home/circleci/project/packages/prosemirror-lwdita-localization/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/evolvedbinary__prosemirror-lwdita-localization` if it exists or add a new declaration (.d.ts) file containing `declare module '@evolvedbinary/prosemirror-lwdita-localization';`
26 import { Localization } from "@evolvedbinary/prosemirror-lwdita-localization";
```
And I think unless we publish @evolvedbinary/prosemirror-lwdita-localization we can't get past it in the CI.
> Fix the config loading process and add the new demo script entry function

- packages/prosemirror-lwdita-demo/cypress/e2e/github-inegration.cy.ts
- packages/prosemirror-lwdita/src/github-integration/request.ts
Replace the petal-demo app with Petal bot
> Use petal bot when redirecting to the install page

- packages/prosemirror-lwdita/config.json
Add petal editor info in the PR description
> Link petal editor

- packages/prosemirror-lwdita-demo/package.json
- packages/prosemirror-lwdita/package.json
- packages/prosemirror-lwdita/tests/test-utils.ts
- yarn.lock
Reverts the changes to the test XML, and update the new patch 3.2.1
> Update to lwdita 3.2.1

- packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
Previously after you installed Petal the first-time, and then tried to use it again for a different page, it would re-prompt you to install it again even though it was already installed correctly. This PR fixes that issue by correctly detecting if Petal is installed.
1. Checkout the branch
2. Fill out the client id and secret in the config
3. Enable cors in the backend config
4. start the demo and the backend
5. Uninstall petal-bot from your GitHub account
6. visit http://localhost:1234/?ghrepo=evolvedbinary/cityehr-documentation&source=cityehr-quick-start-guide/src/main/lwdita/quickstart-guide-modular/verify-install.dita&branch=develop&referer=https://evolvedbinary.github.io/cityehr-documentation/verify-install.html
7. Make sure you are redirected to the petal-bot install page
8. install …
> Make sure the user has installed the GitHub app

- packages/prosemirror-lwdita-demo/cypress/e2e/suggestion-popup.cy.ts
- packages/prosemirror-lwdita-demo/src/example.ts
- packages/prosemirror-lwdita-demo/style/style.scss
- packages/prosemirror-lwdita/src/commands.ts
- packages/prosemirror-lwdita/src/index.ts
- packages/prosemirror-lwdita/src/plugin.ts
- packages/prosemirror-lwdita/src/suggestions-plugin.ts
We want to select which nodes we want to create next in prosemirror.
A pop up with a list of possible next siblings that can be used to select which node to be created next.
<video loop src="https://github.com/user-attachments/assets/d2cc6ed2-2c10-496f-8c84-17837b8184fe">  video </video>
> Suggestion popup for selecting next sibling
