- package.json
- prosemirror-jdita/package.json
- yarn.lock
1. Re-enables the Coveralls.io Code coverage for prosemirror-jdira
2. Has Travis run the Code Coverage targets
> Pass-through the targets for Travis CI

- .circleci/config.yml
Closes https://github.com/evolvedbinary/prosemirror-jdita/pull/185
Improvements to CI, take a multi-job approach, whereby `install packages` happens once up-front and is cached and reused by the following jobs.
> Multi-job CI 

- .gitignore
- prosemirror-jdita-demo/tsconfig.json
- prosemirror-jdita/package.json
- prosemirror-jdita/tsconfig.json
- yarn.lock
We can simplify our tsconfig by using the recommended base. See https://github.com/tsconfig/bases
This also changes the `outDir` from `lib/` to `dist/` which seems to be the convention in JavaScript projects these days.
> Simplify our tsconfig

- config/notice.js
- prosemirror-lwdita/.eslintrc
- prosemirror-lwdita/package.json
- prosemirror-lwdita/src/commands.ts
- prosemirror-lwdita/src/document.ts
- prosemirror-lwdita/src/dom.ts
- prosemirror-lwdita/src/index.ts
- prosemirror-lwdita/src/nodes.ts
- prosemirror-lwdita/src/plugin.ts
- prosemirror-lwdita/src/schema.ts
- prosemirror-lwdita/src/tests/commands.spec.ts
- prosemirror-lwdita/src/tests/document.spec.ts
- prosemirror-lwdita/src/tests/dom.spec.ts
- prosemirror-lwdita/src/tests/schema.spec.ts
- prosemirror-lwdita/src/tests/test-utils.ts
- prosemirror-lwdita/src/tests/topic.spec.ts
- yarn.lock
This uses an eslint plugin to enforce that each .ts source file has the correct Copyright notice and license header.
> Ensure copyright notice and license are present in source files

- packages/prosemirror-lwdita/src/document.ts
- packages/prosemirror-lwdita/src/tests/document.spec.ts
- packages/prosemirror-lwdita/src/tests/test-utils.ts
The round trip was not able to handle text marks from a ProseMirror Document, this PR aims to address that.
> Handle marks in the `untravel` function

- .gitignore
- packages/prosemirror-lwdita-demo/cypress.config.ts
- This PR fixes Cypress artefacts appearing in the revision after running `yarn test:demo`, which includes downloading a file to the filesystem. 
- In addition, it configures Cypress to clear its downloads folder before initiating a test run.
> Remove Cypress test artefacts from revision and clear Cypress downloads folder before each test run

- packages/prosemirror-lwdita-demo/cypress/e2e/newline.cy.ts
- packages/prosemirror-lwdita/src/commands.ts
- packages/prosemirror-lwdita/src/document.ts
- packages/prosemirror-lwdita/src/schema.ts
- packages/prosemirror-lwdita/src/tests/schema.spec.ts
This PR enables inserting line breaks in the middle of text when pressing enter.
> Enable inserting line breaks by pressing enter

- package.json
- packages/prosemirror-lwdita-backend/README.md
- packages/prosemirror-lwdita-backend/package.json
- packages/prosemirror-lwdita-backend/src/server.ts
- packages/prosemirror-lwdita-backend/tsconfig.json
- yarn.lock
Adds another workspace to the prosemirror-lwdita project.
This PR, adds the server boilerplate code to start development.
How to test this PR:
* install the new dependencies by running `yarn install`.
* start the http server by building and starting it.
```shell
$ cd packages/prosemirror-lwdita-backend
$ yarn run build
$ yarn run start
```
* visit http://localhost:3000/ and check for the server response.
> Http server boilerplate

- packages/prosemirror-lwdita-demo/style/style.scss
- packages/prosemirror-lwdita/package.json
- packages/prosemirror-lwdita/src/request.ts
- packages/prosemirror-lwdita/src/tests/request.spec.ts
- packages/prosemirror-lwdita/src/toast.ts
- yarn.lock
This PR provides a functionality that allows to handle requests to the Petal website. 
The request URL will be parsed and validated. 
If the validation succeeds, a parameter object containing key and values will be stored and the user will be shown a "success" notification.
If the parameters don't comply with the expected keys, the user will be shown an "error" notification.
If no parameters were received, an "info" notification will be shown for development purposes (should be deleted later, or get an updated content).
```
rm -rf node_modules/
yarn install
yarn clean && yarn build & yarn start:demo
```
Insert several URLs in the Petal demo page and check the logs and the notifications. You can have a look at the unit tests for tested example parameters to test in the browser.
```
yarn …
```
> Provide a functionality to handle requests

- packages/prosemirror-lwdita-backend/package.json
- packages/prosemirror-lwdita-backend/src/api/controller/github.controller.ts
- packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
- packages/prosemirror-lwdita-backend/src/api/routes/github.router.ts
- yarn.lock
This PR add the functionality to get the user data and creates the endpoint `/api/github/user`.
This Should be look at after #370  is done.
* checkout the branch `octokit/user-data`
* install any new dependencies using `yarn install`
* start the server using `yarn start:backend`
* copy the token you got before from the auth process, or generate a new one by making a request to `https://github.com/login/oauth/authorize?client_id=` add the client id.
* Make a `GET` request to `http://localhost:3000/api/github/user` and the token as a bearer Token in the authorization header.
```sh
curl --location 'localhost:3000/api/github/user' \
--header 'Authorization:bearer ••••••'
```
* the response must contain your GitHub information.
> User Data end point and functions

- packages/prosemirror-lwdita/src/request.ts
- packages/prosemirror-lwdita/src/tests/request.spec.ts
Before, the check for parameters was returning true if only one valid valid key-value pair was found. Now it checks for all of the three key-value pairs to be complete and only then turns "validParams" (true).
> [bugfix] Fix evaluating inclomplete parameter key-value pairs

- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
- packages/prosemirror-lwdita-demo/src/example.ts
- packages/prosemirror-lwdita-demo/style/style.scss
- packages/prosemirror-lwdita/src/request.ts
Display UI elements “Open File” and “Publish” Button depending on called endpoints.
* checkout the branch
* start the demo server `yarn run start:demo`
* set `urlParams` to `false` in `example.ts`
* check the UI changes.
* click the publish button
* check the console for the output from the function `publishGithubDocument`
> Optional UI element for publishing based on URLParams

- packages/prosemirror-lwdita-demo/src/example.ts
- packages/prosemirror-lwdita/package.json
- packages/prosemirror-lwdita/src/github.plugin.ts
- packages/prosemirror-lwdita/src/index.ts
- packages/prosemirror-lwdita/src/tests/github.plugin.spec.ts
- packages/prosemirror-lwdita/src/tests/test-utils.ts
- yarn.lock
This PR adds two new functions that will be used for the GitHub integration:
*  `fetchRawDocumentFromGitHub`  Fetch the Raw document from Github.
*  `transformGitHubDocumentToProsemirrorJson` Transform the `xdita` to `Jdita` then to `prosemirrorJson`.
* checkout the branch
* install new dependencies `yarn install`
* run the tests `yarn run test`
> Fetch Github Raw document And transform to prosemirror document

- packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
This is a temporary fix for the `master` branch issues, where GitHub API returns the wrong value for the default branch.
> Prevent the default branch from returning master

- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
- packages/prosemirror-lwdita/src/config.ts
- packages/prosemirror-lwdita/src/request.ts
- packages/prosemirror-lwdita/src/tests/request.spec.ts
This PR redirects successful redirects to the Petal app to GitHub authentication.
1. Install PR 
```
rm -rf node_modules/
yarn install
yarn clean && yarn build && yarn start:demo
```
2. Open a **new blank tab** and insert a test URL, i.e. `localhost:1234/?ghrepo=ghrepo1&source=source1&referer=referer1` to mock a redirect coming from an external page to Petal.
3. The result should either redirect you to the GitHub Authentication page or directly return the user code if the authentication has been granted in a previous session (note that the toast will indicate "invalid params", because handling the response is out of scope for this PR).
> Redirect users to GitHub to authenticate Github Petal App

- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
- packages/prosemirror-lwdita-demo/style/style.scss
This PR fixes the styling for the new "Publish" button and the old GitHub link buttons in the toolbar-.
Previously the rules for the `.ic-github` class were having side-effects on the other GitHub buttons in the toolbar. 
I have added another class to the publish button in order to specify the css selector and to avoid the side-effects.
> Encapsulate and fix CSS styling for the publish button in the editor toolbar

- packages/prosemirror-lwdita-demo/auth-error.html
- packages/prosemirror-lwdita-demo/package.json
- packages/prosemirror-lwdita-demo/style/style.scss
- packages/prosemirror-lwdita/src/config.ts
- packages/prosemirror-lwdita/src/github-integration/request.ts
- packages/prosemirror-lwdita/tests/request.spec.ts
This PR handles errors during requests depending on the error case and provides feeback to users and redirects to the referrer page, or shows a Petal error page, if no referer parameter has been received or has been stored.
1. Insert different parameters to test all cases.
2. Manipulate the localStorage in the browser devTools: Delete a key, a value to also test if all checks have been implemented correctly.
> Handle user redirect after error / invalid request

- packages/prosemirror-lwdita-demo/src/example.ts
- packages/prosemirror-lwdita/src/github-integration/github.plugin.ts
- packages/prosemirror-lwdita/src/github-integration/request.ts
Fetch the raw document from GitHub then transform it into a prosemirror state json.
* Checkout the branch `git checkout feature/render`
* Install dependencies `yarn install`
* Start the demo `yarn run start:demo`
* Make a request to `http://localhost:1234/?ghrepo=evolvedbinary/prosemirror-lwdita&source=packages/prosemirror-lwdita-demo/example-xdita/02-short-file.xml&referer=htwsrhtshrts`
* Authenticate Petal Github APP 
* `02-short-file.xml` should be rendered on the editor
> Fetch and render the github document if the user opened petal from EDIT ME link

- packages/prosemirror-lwdita-demo/cypress/e2e/image.cy.ts
- packages/prosemirror-lwdita-demo/cypress/e2e/welcome-note.cy.ts
- packages/prosemirror-lwdita-demo/src/example.ts
- packages/prosemirror-lwdita-demo/style/style.scss
- packages/prosemirror-lwdita/src/config.ts
- packages/prosemirror-lwdita/src/github-integration/request.ts
- packages/prosemirror-lwdita/src/github-integration/toast.ts
This PR creates a welcome not on each page load, until the user dismisses the note.
* create custom markup for toastify-js toast
* create custom styling for toast
* create object messageKeys to store, read and maintain content strings in a config file
* store key `welcomeNoteConfirmed` in localStorage if user clicks dismiss button and check on page load if key exists
* remove obsolete toast for case `noParams`
* add option `close: true` to toast for removing the toast only for this session without storing the key into localStorage
1. Install the branch
2. Start the demo `yarn start:demo`
3. Load the page
4. Test to click on the message or the dismiss button and check the localStorage for key `welcomeNoteConfirmed` in the devTools. It should be stored there.
5. Reload the page - the note …
> Display a dismissible welcome note on page load

- packages/prosemirror-lwdita-demo/style/style.scss
- packages/prosemirror-lwdita/src/app-config.ts
- packages/prosemirror-lwdita/src/commands.ts
- packages/prosemirror-lwdita/src/config.ts
- packages/prosemirror-lwdita/src/github-integration/request.ts
- packages/prosemirror-lwdita/src/github-integration/toast.ts
This PR adds 2 new toast types: 
1. A panel-layout notification that stays until dismissed, contains a static message text, and a link to a url passed as an argument. This will be used for success messages after publication.
2. A panel-layout notification that stays until dismissed, contains a static message text, and an error message passed as an argument. This will be used for error messages after publication.
1. Install and build the branch.
2. Test the toasts: 
- Either run the entire publication process with running the local server
- or call the toast functions `showPublicationResultSuccess(<insert a GitHub URL>)`, `showPublicationResultError(<insert a static string>)` in example.ts on page load, but mind that the welcome note will cover the toasts on the first load. You have to …
> Show user notifications for final result after publication

- packages/prosemirror-lwdita-backend/src/api/controller/github.controller.ts
- packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
Introduce `@octokit/plugin-retry` to the backend, And enable it.
This is mainly to prevent 404 and 5xx error from GitHub API.
How to test
1. checkout the branch
2. make sure you have a  clean state: no auth, no fork in your GitHub
3. Go over the GitHub integration process
4. Usually we notice the 404 error related to the branch name not found
5. Notice the error in the terminal output
6. Notice the request was tried again
7. The GitHub integration process should continue even with the 404.
> GitHub API calls retry on error

- packages/prosemirror-lwdita/src/github-integration/github.plugin.ts
- packages/prosemirror-lwdita/tests/github.plugin.spec.ts
Seems like Github updated the raw link urls to include `ref/head` now.
> Update the raw link api

- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
Before, only xml files where allowed to be uploaded via the "Upload" button in the editor.  
Now, also `dita` files can be uploaded.
> Add DITA MIME type and allow `.dita` files to be uploaded to the editor

- packages/prosemirror-lwdita-backend/README.md
The whole `dist` dir is needed when trying to run the backend on production server.
> Copy the whole dist folder

- packages/prosemirror-lwdita-demo/package.json
- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
- packages/prosemirror-lwdita-demo/src/example.ts
- packages/prosemirror-lwdita/package.json
- packages/prosemirror-lwdita/src/github-integration/github.plugin.ts
- yarn.lock
When using Petal Images should point to the base url of the referer.
How to test:
Visit http://dev.petal.evolvedbinary.com/?ghrepo=evolvedbinary/cityehr-documentation&source=cityehr-quick-start-guide/src/main/lwdita/quickstart-guide-modular/verify-install.dita&branch=develop&referer=https://evolvedbinary.github.io/cityehr-documentation/verify-install.html
and check image source.
> Images should point to the base url

- packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
Switched from creating the PR in the user's own fork to the upstream repo.
> Ensure the PR is created in the upstream repository

- plugin-release.js
Enhance the release script and output and make it exist on the first failure.
> Make sure each external command exists with success code

- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
Updates PR - https://github.com/evolvedbinary/prosemirror-lwdita/pull/497 - Fixes retrieving the file name from URL parameters as a string instead of an array.
Fixes retrieving filenames from uploaded files used in the stand-alone editor instead of always displaying the default name.
* get the entire filename and its file ending and store it to the localStorage
* if URL parameters are available for param source, retrieve the string after the last `/` and return it as a string
* if no parameters for source are available, render the filename label that has been stored in localStorage
* if no filename has been stored and no URL parameter has been passed, just render the default fallback, which is the start page file `petal.xml`
> Render filename labels dynamically for "Publish" and "Download" buttons in the editor toolbar.

- packages/prosemirror-lwdita-demo/package.json
- packages/prosemirror-lwdita/package.json
- packages/prosemirror-lwdita/tests/test-utils.ts
- yarn.lock
Update to use the latest lwdita library, The changes from the serializer work can be seen here https://github.com/marmoure/cityehr-documentation/pull/3/files
* no extra white-space
* correct doctype
* images are acting nice
There was changes to the tests xml for the `image` and `fallback` as both can not have whitespace in them now, this is due to the `alt` node being considered mixed content
> [feature] update to lwdita 3.2.0

- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
- packages/prosemirror-lwdita-demo/src/example.ts
This was always set to "petal.xml"
> File name should be picked up from the url params

- .circleci/config.yml
- README.md
- packages/prosemirror-lwdita-demo/README.md
The PR fixes the CI and allows for cypress tests to run again.
> Build the project before running cypress

- packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
- packages/prosemirror-lwdita-demo/src/demo-plugin.ts
- packages/prosemirror-lwdita/src/commands.ts
- packages/prosemirror-lwdita/src/github-integration/request.ts
- packages/prosemirror-lwdita/tests/topic.spec.ts
There were console.log instances in the code that are obsolete and some were not needed, while some other error logs were marked as simple logs.
This PR removes some of those logs and fixes others.
> Remove obsolete console.log and fix the error logs

- packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
When you create a PR from fork to upstream, the commit changes will show from an older commit not the head of the upstream, ex
A PRs made from the fork to upstream but it shows more changes then it really happned:
https://github.com/marmoure/xdita-sample/pull/3/files
The new breach created by petal-bot will be pointing towards the upstream target branch head ,and not the fork one, this will ensure that the branch is always up to date, with what we want to change.
Here are two PRs created by me from the same state one with the fix and one without
https://github.com/marmoure/xdita-sample/pull/7/files
https://github.com/marmoure/xdita-sample/pull/8/files
Notice how the PR number 8 shows unwanted changes.
1. Checkout main
2. You have to edit the config files (DM me)
3. Open …
> Always branch off from the upstream branch, not the fork

- package.json
- packages/prosemirror-lwdita-demo/package.json
The demo package is not a lib that you can import to your project and there's no point of publishing it.
Set the demo package to private to make sure it's never going to be published, and also remove the demo from the publish script.
The demo package should be Deleted from `npm`, THIS NEEDS TO BE DONE BY @adamretter.
1. Bump the version to "2.5.2"
2. run `yarn publish`
3. Note that the demo package did not get published
> Stop publishing the demo package as it's not a lib

- packages/prosemirror-lwdita-demo/package.json
- packages/prosemirror-lwdita/package.json
- packages/prosemirror-lwdita/tests/test-utils.ts
- packages/prosemirror-lwdita/tests/topic.spec.ts
- yarn.lock
This PR updates the lwdita version to 3.3.0, Also fixes to the doctype header were added.
> Update to use lwdita 3.3.0

- packages/prosemirror-lwdita-demo/cypress/e2e/round-trip.cy.ts
Adds Cypress tests for checking the custom doctype and xml declaration after the full transformation.
Related to https://github.com/evolvedbinary/lwdita/pull/323.
Should only be reviewed after #506 is done, and https://github.com/evolvedbinary/lwdita/pull/323 merged, and added to the project.
> Round trip test for doctype and xml declaration
